
CREATE TABLE [DIM_GENDER] (
	GENDER_KEY INT IDENTITY(1,1) PRIMARY KEY,
	GENDER NVARCHAR(500)
)

CREATE TABLE [DIM_EMPLOYMENT] (
	EMPLOYMENT_KEY INT IDENTITY(1,1) PRIMARY KEY,
	EMPLOYMENT_STATUS NVARCHAR(500)
)

CREATE TABLE [DIM_INCOME_BAND] (
	INCOME_BAND_KEY INT IDENTITY(1,1) PRIMARY KEY,
	INCOME_BAND_NAME NVARCHAR(500),
	MIN_INCOME DECIMAL(18,0),
	MAX_INCOME DECIMAL(18,0)
)

CREATE TABLE [DIM_PROPERTY] (
	PROPERTY_KEY INT IDENTITY(1,1) PRIMARY KEY,
	PROPERTY_OWNERSHIP_STATUS NVARCHAR(500),
)

CREATE TABLE [DIM_CIBIL_BAND] (
	CIBIL_BAND_KEY INT IDENTITY(1,1) PRIMARY KEY,
	CIBIL_BAND_NAME NVARCHAR(500),
	MIN_CIBIL INT,
	MAX_CIBIL INT,
)

CREATE TABLE [DIM_ADDRESS] (
	ADDRESS_KEY INT IDENTITY(1,1) PRIMARY KEY,
	RESIDENTIAL_ADDRESS NVARCHAR(500),
	CITY NVARCHAR(500),
	STATE NVARCHAR(500),
)

CREATE TABLE [DIM_CUSTOMER] (
	CUSTOMER_KEY INT IDENTITY(1,1) PRIMARY KEY,
	CUSTOMER_ID NVARCHAR(500),
	GENDER_KEY INT,
	NUMBER_OF_DEPENDENTS INT,
	EMPLOYMENT_KEY INT,
	MONTHLY_INCOME DECIMAL(18,0),
	INCOME_BAND_KEY INT,
	ADDRESS_KEY INT,
	PROPERTY_KEY INT,
	CIBIL_SCORE INT,
	CIBIL_BAND_KEY INT,

	CONSTRAINT GENDER_FK FOREIGN KEY(GENDER_KEY)
		REFERENCES DIM_GENDER(GENDER_KEY),
	CONSTRAINT EMPLOYMENT_FK FOREIGN KEY(EMPLOYMENT_KEY)
		REFERENCES DIM_EMPLOYMENT(EMPLOYMENT_KEY),
	CONSTRAINT INCOME_BAND_FK FOREIGN KEY(INCOME_BAND_KEY)
		REFERENCES DIM_INCOME_BAND(INCOME_BAND_KEY),
	CONSTRAINT ADDRESS_FK FOREIGN KEY(ADDRESS_KEY)
		REFERENCES DIM_ADDRESS(ADDRESS_KEY),
	CONSTRAINT PROPERTY_FK FOREIGN KEY(PROPERTY_KEY)
		REFERENCES DIM_PROPERTY(PROPERTY_KEY),
	CONSTRAINT CIBIL_FK FOREIGN KEY(CIBIL_BAND_KEY)
		REFERENCES DIM_CIBIL_BAND(CIBIL_BAND_KEY),
)


CREATE TABLE [DIM_PURPOSE] (
	PURPOSE_KEY INT IDENTITY(1,1) PRIMARY KEY,
	PURPOSE_OF_LOAN NVARCHAR(500)
)

CREATE TABLE [DIM_LOAN_TYPE] (
	LOAN_TYPE_KEY INT IDENTITY(1,1) PRIMARY KEY,
	LOAN_TYPE NVARCHAR(500),
)

CREATE TABLE [DIM_LOAN_STATUS] (
	LOAN_STATUS_KEY INT IDENTITY(1,1) PRIMARY KEY,
	LOAN_STATUS NVARCHAR(500)
)

CREATE TABLE [DIM_FRAUD] (
	FRAUD_KEY INT IDENTITY (1,1) PRIMARY KEY,
	FRAUD_FLAG INT
)

CREATE TABLE [FACT_LOAN_APPLICATION] (
	APPLICATION_KEY INT IDENTITY(1,1) PRIMARY KEY,
	APPLICATION_ID NVARCHAR(500),
	LOAN_AMOUNT_REQUESTED DECIMAL(18,2),
	LOAN_TENURE_MONTHS INT,
	INTEREST_RATE_OFFERED DECIMAL(9,6),
	EXISTING_EMIS_MONTHLY DECIMAL(18,2),
	DEBT_TO_INCOME_RATIO DECIMAL(9,6),
	APPLICANT_AGE INT,
	PURPOSE_KEY INT,
	LOAN_TYPE_KEY INT,
	LOAN_STATUS_KEY INT,
	CUSTOMER_KEY INT,
	FRAUD_KEY INT,

	CONSTRAINT PURPOSE_FK FOREIGN KEY(PURPOSE_KEY)
		REFERENCES DIM_PURPOSE(PURPOSE_KEY),
	CONSTRAINT LOAN_TYPE_FK FOREIGN KEY(LOAN_TYPE_KEY)
		REFERENCES DIM_LOAN_TYPE(LOAN_TYPE_KEY),
	CONSTRAINT LOAN_STATUS_FK FOREIGN KEY(LOAN_STATUS_KEY)
		REFERENCES DIM_LOAN_STATUS(LOAN_STATUS_KEY),
	CONSTRAINT CUSTOMER_FK FOREIGN KEY(CUSTOMER_KEY)
		REFERENCES DIM_CUSTOMER(CUSTOMER_KEY),
	CONSTRAINT FRAUD_FK FOREIGN KEY(FRAUD_KEY)
		REFERENCES DIM_FRAUD(FRAUD_KEY)
)





INSERT INTO DIM_CIBIL_BAND (CIBIL_BAND_NAME, MIN_CIBIL, MAX_CIBIL)
VALUES 
 ('POOR', 300, 579),
 ('FAIR', 580, 669),
 ('GOOD', 670, 739),
 ('VERY GOOD', 740, 799),
 ('EXCELLENT', 800, 850);

 INSERT INTO DIM_INCOME_BAND (INCOME_BAND_NAME,MIN_INCOME,MAX_INCOME) VALUES
 ('VERY LOW', 0, 19999),
 ('LOW', 20000, 39999),
 ('LOWER MIDDLE', 40000, 74999),
 ('MIDDLE', 75000, 124999),
 ('UPPER MIDDLE', 125000, 199999),
 ('HIGH', 200000, 349999),
 ('VERY HIGH', 350000, NULL);