DELETE FROM DIM_CUSTOMER;
DBCC CHECKIDENT ('DIM_CUSTOMER', RESEED, 0);
DELETE FROM FACT_LOAN_APPLICATION;
DBCC CHECKIDENT ('FACT_LOAN_APPLICATION', RESEED, 0);

DELETE FROM DIM_GENDER;
DBCC CHECKIDENT ('DIM_GENDER', RESEED, 0);
DELETE FROM DIM_EMPLOYMENT;
DBCC CHECKIDENT ('DIM_EMPLOYMENT', RESEED, 0);
DELETE FROM DIM_PROPERTY;
DBCC CHECKIDENT ('DIM_PROPERTY', RESEED, 0);
DELETE FROM DIM_ADDRESS;
DBCC CHECKIDENT ('DIM_ADDRESS', RESEED, 0);
DELETE FROM DIM_CIBIL_BAND;
DBCC CHECKIDENT ('DIM_CIBIL_BAND', RESEED, 0);
DELETE FROM DIM_INCOME_BAND;
DBCC CHECKIDENT ('DIM_INCOME_BAND', RESEED, 0);
DELETE FROM DIM_FRAUD;
DBCC CHECKIDENT ('DIM_FRAUD', RESEED, 0);

DELETE FROM DIM_PURPOSE;
DBCC CHECKIDENT ('DIM_PURPOSE', RESEED, 0);
DELETE FROM DIM_LOAN_TYPE;
DBCC CHECKIDENT ('DIM_LOAN_TYPE', RESEED, 0);
DELETE FROM DIM_LOAN_STATUS;
DBCC CHECKIDENT ('DIM_LOAN_STATUS', RESEED, 0);
DELETE FROM DIM_APPLICATION_DATE;
DBCC CHECKIDENT ('DIM_APPLICATION_DATE', RESEED, 0);



