
select * from DIM_EMPLOYMENT;
select * from DIM_PROPERTY;
select * from DIM_ADDRESS;
select * from DIM_INCOME_BAND;
select * from DIM_CIBIL_BAND;
select * from DIM_CUSTOMER;
select * from DIM_GENDER;
select * from DIM_PURPOSE;
select * from DIM_LOAN_TYPE;
select * from DIM_LOAN_STATUS;
select * from FACT_LOAN_APPLICATION;
select * from DIM_FRAUD;
select * from DIM_APPLICATION_DATE;
select distinct(YEAR) from DIM_APPLICATION_DATE;

SELECT 'DIM_EMPLOYMENT'        AS [TableName], COUNT(*) AS [RowCount] FROM dbo.DIM_EMPLOYMENT
UNION ALL
SELECT 'DIM_PROPERTY'          AS [TableName], COUNT(*) AS [RowCount] FROM dbo.DIM_PROPERTY
UNION ALL
SELECT 'DIM_ADDRESS'           AS [TableName], COUNT(*) AS [RowCount] FROM dbo.DIM_ADDRESS
UNION ALL
SELECT 'DIM_INCOME_BAND'       AS [TableName], COUNT(*) AS [RowCount] FROM dbo.DIM_INCOME_BAND
UNION ALL
SELECT 'DIM_CIBIL_BAND'        AS [TableName], COUNT(*) AS [RowCount] FROM dbo.DIM_CIBIL_BAND
UNION ALL
SELECT 'DIM_CUSTOMER'          AS [TableName], COUNT(*) AS [RowCount] FROM dbo.DIM_CUSTOMER
UNION ALL
SELECT 'DIM_GENDER'            AS [TableName], COUNT(*) AS [RowCount] FROM dbo.DIM_GENDER
UNION ALL
SELECT 'DIM_PURPOSE'           AS [TableName], COUNT(*) AS [RowCount] FROM dbo.DIM_PURPOSE
UNION ALL
SELECT 'DIM_LOAN_TYPE'         AS [TableName], COUNT(*) AS [RowCount] FROM dbo.DIM_LOAN_TYPE
UNION ALL
SELECT 'DIM_LOAN_STATUS'       AS [TableName], COUNT(*) AS [RowCount] FROM dbo.DIM_LOAN_STATUS
UNION ALL
SELECT 'DIM_FRAUD'             AS [TableName], COUNT(*) AS [RowCount] FROM dbo.DIM_FRAUD
UNION ALL
SELECT 'DIM_APPLICATION_DATE'  AS [TableName], COUNT(*) AS [RowCount] FROM dbo.DIM_APPLICATION_DATE
UNION ALL
SELECT 'FACT_LOAN_APPLICATION' AS [TableName], COUNT(*) AS [RowCount] FROM dbo.FACT_LOAN_APPLICATION
ORDER BY [TableName];
