-- Bảng chương trình
CREATE TABLE [DIM_PROGRAM] (
	PROGRAM_ID INT IDENTITY(1,1) PRIMARY KEY,
	TITLE NVARCHAR(max) NULL,
	DESCRIPTION NVARCHAR(MAX),
	PROGRAM_LENGTH FLOAT,
	TIME_PER_WORKOUT FLOAT,
	TOTAL_EXERCISE_IN_PROGRAM FLOAT,
	CREATED DATETIME,
	LAST_EDIT DATETIME
);

-- Bảng cấp độ (level)
CREATE TABLE [DIM_LEVEL] (
	LEVEL_ID INT IDENTITY(1,1) PRIMARY KEY,
	LEVEL_NAME NVARCHAR(max) null
);

-- Bảng nối nhiều-nhiều giữa chương trình và level
CREATE TABLE [DIM_PROGRAM_LEVEL] (
	PROGRAM_ID INT,
	LEVEL_ID INT,
	PRIMARY KEY(PROGRAM_ID, LEVEL_ID),
	FOREIGN KEY(PROGRAM_ID) REFERENCES DIM_PROGRAM(PROGRAM_ID),
	FOREIGN KEY(LEVEL_ID) REFERENCES DIM_LEVEL(LEVEL_ID)
);

-- Bảng mục tiêu (goal)
CREATE TABLE [DIM_GOAL] (
	GOAL_ID INT IDENTITY(1,1) PRIMARY KEY,
	GOAL_NAME NVARCHAR(max)
);

ALTER TABLE DIM_GOAL
ALTER COLUMN GOAL_NAME NVARCHAR(max) null;
-- Bảng nối chương trình và mục tiêu
CREATE TABLE [DIM_PROGRAM_GOAL] (
	PROGRAM_ID INT,
	GOAL_ID INT,
	PRIMARY KEY(PROGRAM_ID, GOAL_ID),
	FOREIGN KEY(PROGRAM_ID) REFERENCES DIM_PROGRAM(PROGRAM_ID),
	FOREIGN KEY(GOAL_ID) REFERENCES DIM_GOAL(GOAL_ID)
);

-- Bảng bài tập (exercise)
CREATE TABLE [DIM_EXERCISE] (
	EXERCISE_ID INT IDENTITY(1,1) PRIMARY KEY,
	EXERCISE_NAME NVARCHAR(max),
	NUMBER_OF_SET FLOAT,
	NUMBER_OF_REP FLOAT,
	INTENSITY FLOAT,
	CREATED DATETIME,
	LAST_EDIT DATETIME
);


ALTER TABLE DIM_EXERCISE
ALTER COLUMN EXERCISE_NAME NVARCHAR(max) null;
-- Bảng nối 3 chiều giữa program, level và exercise
CREATE TABLE [DIM_PROGRAM_LEVEL_EXERCISE] (
	PROGRAM_ID INT,
	LEVEL_ID INT,
	EXERCISE_ID INT,
	POSITION_WEEK INT,
	POSITION_DAY INT,
	NUMBER_OF_EXERCISE INT,
	PRIMARY KEY(PROGRAM_ID, LEVEL_ID, EXERCISE_ID),
	FOREIGN KEY(PROGRAM_ID, LEVEL_ID) REFERENCES DIM_PROGRAM_LEVEL(PROGRAM_ID, LEVEL_ID),
	FOREIGN KEY(EXERCISE_ID) REFERENCES DIM_EXERCISE(EXERCISE_ID)
);

-- Bảng thiết bị (equipment)
CREATE TABLE [DIM_EQUIPMENT] (
	EQUIPMENT_ID INT IDENTITY(1,1) PRIMARY KEY,
	EQUIPMENT_NAME NVARCHAR(50)
);

-- Bảng nối chương trình và thiết bị
CREATE TABLE [DIM_PROGRAM_EQUIPMENT] (
	PROGRAM_ID INT,
	EQUIPMENT_ID INT,
	PRIMARY KEY(PROGRAM_ID, EQUIPMENT_ID),
	FOREIGN KEY(PROGRAM_ID) REFERENCES DIM_PROGRAM(PROGRAM_ID),
	FOREIGN KEY(EQUIPMENT_ID) REFERENCES DIM_EQUIPMENT(EQUIPMENT_ID)
);

select * from DIM_PROGRAM;
select * from DIM_LEVEL;
select * from DIM_EXERCISE;
select * from DIM_EQUIPMENT;

